name: Build

on:
    workflow_run:
        workflows: [Check]
        branches: "**"
        types:
            - completed
    workflow_dispatch:
        inputs:
            use-build-cache:
                type: boolean
                required: true
                description: "Use existing caches builds for incremental building"

jobs:
    build:
        name: Build ${{ github.sha }} of ${{ github.repository }}
        if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              id: pnpm-install
              with:
                  version: 10
                  run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version-file: "package.json"
                  cache: "pnpm"
            - name: Set up upload-only build cache
              if: github.event_name == 'workflow_dispatch' && inputs.use-build-cache == false
              uses: actions/cache@v4
              with:
                  path: dist
                  key: cf-pages-build-${{ github.sha }}
            - name: Set up build cache with restore
              if: github.event_name != 'workflow_dispatch' || inputs.use-build-cache == true
              uses: actions/cache@v4
              with:
                  path: dist
                  key: cf-pages-build-${{ github.sha }}
                  restore-keys: cf-pages-build-
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
